### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by ghamaide** [DispatcherInc/react-native-branch#2]
Hey, thanks for the great work ! Do you have any idea of when you'll be able to release an Android version ? Cheers again for the work !

**Comment by kevinstumpf** [comment]
Hey! Unfortunately I don't have a fixed release date in mind yet, but I'll try to get it out before the end of the month. If you need it sooner, feel free to create a pull request for it, though :)

**Comment by ghamaide** [comment]
Any updates ? (I've never done Java before, else I'd try and submit a PR ;))

**Comment by kevinstumpf** [comment]
Not yet, sorry. I need a few more days.

This might be a great opportunity to skim and learn the surface of Java ;)

**Comment by kevinstumpf** [comment]
@ghamaide - Just added Android support.

Please let me know if you run into any issues.

**Comment by ghamaide** [comment]
Awesome ! I'll jump into it asap and will let you know. Thanks !

**Comment by ghamaide** [comment]
Tested it, seems to work like a charm. Thanks !!

**Comment by kevinstumpf** [comment]
:+1:
